channels:
- pytorch
- conda-forge
- defaults
dependencies:
- numpy=1.24.3=py38h14f4228_0
- numpy-base=1.24.3=py38h31eccc5_0
- pandas=2.0.2=py38h01efb38_0
- pillow=9.4.0=py38hde6dc18_1
- sqlalchemy=2.0.17=py38h01eb140_0
- torchaudio=0.10.1=py38_cu113
- torchvision=0.11.2=py38_cu113
- pip:
  - absl-py==1.4.0
  - alabaster==0.7.13
  - antlr4-python3-runtime==4.9.3
  - asttokens==2.2.1
  - attrs==23.1.0
  - babel==2.12.1
  - backcall==0.2.0
  - beautifulsoup4==4.12.2
  - blessed==1.20.0
  - cachetools==5.3.1
  - captum==0.2.0
  - charset-normalizer==3.1.0
  - cilog==1.2.3
  - cloudpickle==2.2.1
  - coverage==7.2.7
  - cvxopt==1.3.1
  - decorator==5.1.1
  - dive-into-graphs==1.1.0
  - docutils==0.17.1
  - et-xmlfile==1.1.0
  - execnet==1.9.0
  - executing==1.2.0
  - filelock==3.12.2
  - gdown==4.7.1
  - google-auth==2.21.0
  - google-auth-oauthlib==0.4.6
  - gpustat==1.1.1
  - grpcio==1.56.0
  - h5py==3.9.0
  - hydra-core==1.3.2
  - idna==3.4
  - imagesize==1.4.1
  - importlib-metadata==6.7.0
  - iniconfig==2.0.0
  - ipython==8.12.2
  - jedi==0.18.2
  - jinja2==3.1.2
  - joblib==1.2.0
  - kmeans-pytorch==0.3
  - littleutils==0.2.2
  - llvmlite==0.40.1
  - markdown==3.4.3
  - markupsafe==2.1.3
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.6
  - mpmath==1.3.0
  - munch==2.5.0
  - mypy-extensions==1.0.0
  - networkx==2.8
  - numba==0.57.1
  - nvidia-ml-py==12.535.133
  - oauthlib==3.2.2
  - ogb==1.3.6
  - omegaconf==2.3.0
  - openpyxl==3.1.2
  - outdated==0.2.2
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pluggy==1.2.0
  - prompt-toolkit==3.0.38
  - protobuf==3.20.1
  - psutil==5.9.5
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - py==1.11.0
  - pyasn1==0.5.0
  - pyasn1-modules==0.3.0
  - pygments==2.15.1
  - pynvml==11.5.0
  - pyscf==2.2.1
  - pysocks==1.7.1
  - pytest==7.1.2
  - pytest-cov==3.0.0
  - pytest-forked==1.6.0
  - pytest-xdist==2.5.0
  - pyyaml==6.0
  - rdkit-pypi==2022.9.5
  - requests==2.31.0
  - requests-oauthlib==1.3.1
  - rsa==4.9
  - ruamel-yaml==0.17.21
  - ruamel-yaml-clib==0.2.7
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - setuptools==59.5.0
  - shap==0.41.0
  - slicer==0.0.7
  - snowballstemmer==2.2.0
  - soupsieve==2.4.1
  - sphinx==5.3.0
  - sphinx-rtd-theme==1.0.0
  - sphinxcontrib-applehelp==1.0.4
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==2.0.1
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.5
  - stack-data==0.6.2
  - sympy==1.12
  - tabulate==0.9.0
  - tensorboard==2.8.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - threadpoolctl==3.1.0
  - tomli==2.0.1
  - torch-geometric==2.0.4
  - torch-scatter==2.0.9
  - torch-sparse==0.6.13
  - tqdm==4.64.0
  - traitlets==5.9.0
  - typed-argument-parser==1.7.2
  - typing-inspect==0.9.0
  - urllib3==1.26.16
  - wcwidth==0.2.6
  - werkzeug==2.3.6
name: pygood
