includes:
  - ../base.yaml
extra_param:
  - # [0] CIA lambda, Match DG lambda
    - 0.1
    - 0.05
    - 0.01
    - 0.005
    - 0.001
    - 0.0005
    - 0.0001
  - # [1] 0: CIA; 1: CIA-LRA; 2:MatchDG
    - 1
  - # [2] CIA-LRA hops t
    - 2
    - 3
    - 4
    - 5
    - 6
  - # [3] CIA-LRA lambda
    - 0.05
    - 0.01
    - 0.005
    - 0.001
    - 0.0005
    - 0.0001
  - # [10] if CIA gt loss
    - 2 # 1:CIA 2:MatchDG
