includes:
  - base.yaml
model:
  model_name: CIGAmsGIN
ood:
  ood_alg: CIGAms
  ood_param: 0.3
  extra_param:
    - 2
    - 1
    - 0.5
    - 0.5
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
log_file: default
