includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGAls_abl
  ood_param: 0.3
  extra_param:
    - -1
    - 1
    - 0.5
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
log_file: default
