includes:
  - base.yaml
model:
  model_name: CIGAdivGIN
ood:
  ood_alg: CIGAdiv
  ood_param: 0.3
  extra_param:
    - 2
    - 1
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
log_file: default
