includes:
  - base.yaml
model:
  model_name: GCNconda activate /data1/qxwang/conda_envs/pygood
goodtl --sweep_root sweep_configs\
    --launcher MultiLauncher\
    --allow_datasets GOODCBAS\
     --allow_domains color\
      --allow_shifts concept\
       --allow_algs IGA\
        --allow_devices 8
ood:
  ood_alg: IGA
  ood_param: 10.
train:
  max_epoch: 15
  lr: 1e-3
  mile_stones: [150]

