includes:
  - base.yaml
model:
  model_name: EER_MGCN
ood:
  ood_alg: EER_M
  ood_param: 3.
  extra_param:
    - 10   # K: Number of context generator
    - 1   # T
    - 2   # Number of sample
    - 5e-3    # Learning rate for REINFORCE
train:
  max_epoch: 100
  lr: 5e-3
  mile_stones: [150]
