includes:
  - base.yaml
model:
  model_name: CIGAdivGIN
ood:
  ood_alg: CIGAdiv
  ood_param: 0.6
  extra_param:
    - 2
    - 1
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 300
  train_bs: 128
  val_bs: 128
  test_bs: 128
log_file: default
