includes:
  - ../base.yaml
ood_param:
  - 0.5
  - 1.
  - 3.
extra_param:
  - # k: num_envs
    - 7 
  - # t: AT steps
    - 1
    #- 5
  - # s:how many nodes for each node should be modified the link with 
    #- 1
    - 5
  -
    - 1e-2
    - 5e-3
    - 1e-3
    - 1e-4